In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [24]:
# write your code here ^_^

x = np.ones((3, 3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Q#2: Create y array with elements equal to 0.

In [25]:
# write your code here ^_^

y = np.zeros((3, 3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q#3: Add x and y arrays.

In [26]:
# write your code here ^_^

z = x + y
print(z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [27]:
# write your code here ^_^

print("Dimension:", x.ndim)               
print("The shape is :", x.shape)
print("The size is :", x.size)
print("The type is :", type(x))
print("The elemnts type is :", x.dtype)

Dimension: 2
The shape is : (3, 3)
The size is : 9
The type is : <class 'numpy.ndarray'>
The elemnts type is : float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [28]:
# write your code here ^_^

w = np.array([[11, 12], 
              [13, 14], 
              [15, 16]])
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [51]:
# write your code here ^_^
z = np.array(([[1],
               [2],
               [3]]))
print(z)

[[1]
 [2]
 [3]]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [100]:
# write your code here ^_^

newArray = np.hstack((z, w))         # Combine z and w horizontally

print(newArray)


[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [57]:
# write your code here ^_^

for row in newArray:
    for element in row:
        print(element)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [104]:
# write your code here ^_^

print("The original array : \n", newArray)

reversedArray = np.flip(newArray, axis=0)                  # Reverse the columns
print("Reverse the columns : \n", reversedArray) 

reversedArray = np.flip(newArray, axis=1)                     # Reverse the rows
print("Reverse the rows : \n", reversedArray)

reversedArray = np.flip(np.flip(newArray, axis=0), axis=1)      # Reverse the columns and rows of newArray by using the axis 0 and 1
print("Reverse the columns and rows : \n", reversedArray)

The original array : 
 [[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]
Reverse the columns : 
 [[ 3 15 16]
 [ 2 13 14]
 [ 1 11 12]]
Reverse the rows : 
 [[12 11  1]
 [14 13  2]
 [16 15  3]]
Reverse the columns and rows : 
 [[16 15  3]
 [14 13  2]
 [12 11  1]]


## Q#10: Decrement all elements of "newArray" with 1.

In [68]:
# write your code here ^_^

newArray -= 1
print(newArray)

[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]


## Q#11: Find smallest and biggest values in "newArray".

In [72]:
# write your code here ^_^

BiggestValue = newArray.max()
print("The Biggest Value is : ", BiggestValue)

SmallestValue = newArray.min()
print("The Biggest Value is : ", SmallestValue)


The Biggest Value is :  15
The Biggest Value is :  0


## Q#12: Print the first row of "newArray" using indexing.

In [76]:
# write your code here ^_^

# we can use these tow Ways :
print(newArray[0])
print(newArray[0][::])


[ 0 10 11]
[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [79]:
# write your code here ^_^

print(newArray[1][1])  # the number 12 is in the second row "so its in the index 1", and in the second column "in the index 1 also"

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [87]:
# write your code here ^_^

print("print the number 0 at the index [0][0]: ", newArray[0][0])
print("print the number 13 at the index [1][2]: ", newArray[1][2])

print the number 0 at the index [0][0]:  0
print the number 13 at the index [1][2]:  13


## Q#15: Change the shape of "newArray" to (9,1).

In [96]:
# write your code here ^_^

# we can use tow ways to do it :
newArray_flat = newArray.reshape(9,)        # Reshape newArray into a 1D array with 9 elements, called flattened array
print("Flattened array:")
print(newArray_flat)

newArray_2d = newArray.reshape(9, 1)         # Reshape newArray into a 2D array with 9 rows and 1 column
print("\n2D array:")
print(newArray_2d)

Flattened array:
[ 0 10 11  1 12 13  2 14 15]

2D array:
[[ 0]
 [10]
 [11]
 [ 1]
 [12]
 [13]
 [ 2]
 [14]
 [15]]


## Q#16: Change the shape of "newArray" to (3,3).

In [98]:
# write your code here ^_^

newArray_3x3 = newArray.reshape(3, 3)   
print("\n3 x 3 array:")
print(newArray_3x3)


3 x 3 array:
[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]


# Well Done 🎉